export const EXAMPLE_ACTION = "EXAMPLE_ACTION";

//Global Actions
export const Global = {
  GET: "PUBLICATION.GET",
  GET_SUCCESS: "PUBLICATION.GET_SUCCESS",
  GET_FAILED: "PUBLICATION.GET_FAILED"
};
