//Global Actions
export const EXAMPLE_ACTION = "EXAMPLE_ACTION";

//Publication Actions
export const Publication = {
  GET: "PUBLICATION.GET",
  GET_SUCCESS: "PUBLICATION.GET_SUCCESS",
  GET_FAILED: "PUBLICATION.GET_FAILED",

  GET_LIST: "PUBLICATION.GET_LIST",
  GET_LIST_SUCCESS: "PUBLICATION.GET_LIST_SUCCESS",
  GET_LIST_FAILED: "PUBLICATION.GET_LIST_FAILED",
  SET_LIST_PAGE: "PUBLICATION.SET_LIST_PAGE",

  GET_COMMENTS_LIST: "PUBLICATION.GET_COMMENTS_LIST",
  GET_COMMENTS_LIST_SUCCESS: "PUBLICATION.GET_COMMENTS_LIST_SUCCESS",
  GET_COMMENTS_LIST_FAILED: "PUBLICATION.GET_COMMENTS_LIST_FAILED",
  GET_COMMENTS_LIST_PAGE: "PUBLICATION.SET_COMMENTS_LIST_PAGE"
};
